defaults:
  - fat_default

phase: "phase3"
batch_size: 128
workers: 16
crop_size: 288
lr_epochs:
  - 12
  - 15
lr_values:
  - 0.004
  - 0.0004
start_epoch: 12
end_epoch: 15
resume: "${train_test.model_dir}/phase2/ckpt_epoch12.pt"